music_server:
  address: "localhost:8080"
listeners:
  [
    { address: "localhost:8082" },
    { address: "localhost:8083" },
    { address: "localhost:8084" },
    { address: "localhost:8085" },
  ]
redis:
  address: "localhost:6379"
  password: ""
  db: 0
  ttl: "10s"
